### ISSUE TITLE
Can't open mobile menu or scrollToTop

### ISSUE THREAD

**Issue by rhizoet** [okkur/syna#679] opened 2020-01-07 22:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
In mobile mode I can't open the menu. When I click on the hamburger menu nothing happens.
Same for the ScrollToTop Button - but theres the bug in desktop and mobile mode.

In the demo the bugs are also present.

**What you expected to happen**:
The menu should open and the button should scroll me to the top of the page.

**How to reproduce it (as minimally and precisely as possible)**:
Local install without any configuration and the demo: https://themes.gohugo.io/theme/syna/

**Anything else we need to know?**:
Nothing special here.

**Environment**:
- Syna Theme version:  Latest commit 94d6a04
- Hugo version:  v0.62.0-6608F155/extended
- Others: -

**Comment by stp-ip** [comment] 2020-01-08 16:45
Duplicate of #677 as far as I can see.
PR is in flight: https://github.com/okkur/syna/pull/678

**Closed** 2020-01-11 19:24 UTC
Labels: bug

**Comment by stp-ip** [comment] 2020-01-11 19:30
This should be fixed with #681 in master. Let us know, if anything else comes up. Happy for you to test the latest change. Adding tests for this regression as well.
