### ISSUE TITLE
Generated `index.html` broken when using `baseURL` with path

### ISSUE THREAD

**Issue by sdirix** [okkur/syna#617] opened 2019-10-21 15:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
We are using a `baseURL` with a path like `https://www.example.com/mysite`. When running `hugo server` everything works as expected. However building the site with `hugo` leads to a broken `index.html` in which the `src`-links to Javascript files are misconfigured, for example the `syna-head.min` `script` `src` attribute starts with `/mysite/mysite/scripts/syna....` which is one more `/mysite` than expected.

**What you expected to happen**:
The `index.html` file should be properly generated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup [syna-start](https://github.com/okkur/syna-start)
2. Configure `baseurl` in `config.toml` with `https://example.com/mysite`.
3. Execute `hugo`
4. Check generated `index.html` file in which all script links are broken with `/mysite/mysite`

**Other information**:

I fixed the theme locally by replacing `$script.RelPermalink` with `$script.Permalink` in `layouts/partials/head.html` and `layouts/partials/js.html` but it feels like I'm fighting against the symptom, not the cause of the issue.

**Comment by mpourismaiel** [comment] 2019-10-27 16:36
Thanks for reporting the issue. The problem is indeed with Hugo's own `RelPermalink`. It shouldn't prepend the base url but for some reason it does. I'm investigating the issue but in the meanwhile, change the `js.html` and `head.html` partials locally. If a solution is not found or there's a valid reason for prepending the base url I'll change the theme accordingly.

**Comment by sdirix** [comment] 2019-10-28 10:47
@mpourismaiel Thanks for the response! Yes, it's especially strange as it works in other elements like `$style.RelPermalink`. It's only incorrect for `$script.RelPermalink`.

Will you follow up with the Hugo team?

**Comment by mpourismaiel** [comment] 2019-10-28 11:29
I'll follow up with Hugo's team and see what's the problem.

**Comment by camrinbraun** [comment] 2019-11-22 03:15
Having this same issue. @mpourismaiel what exactly do you mean by "change the ```js.html``` and `head.html` partials locally"?

For example I see the following in `js.html`:
```
...
{{- safeHTMLAttr (printf " src=\"%s\"" ($script.RelPermalink | relLangURL)) -}}></script>
...
```

Thanks!

**Comment by sdirix** [comment] 2019-11-22 07:32
@camrinbraun You can check [this commit](https://github.com/eclipsesource/syna/commit/db7d44890f0ed6f08b15cbb5d71d811255c80b31)

**Comment by camrinbraun** [comment] 2019-11-22 16:03
@sdirix for some reason that doesn't do it for me. I modified `js.html` and `head.html` as in the referenced commit and the links still point to `.../mysite/mysite/...`

I thought maybe it was a rendering issue but I tried
```
hugo server --disableFastRender
```
with no improvement.

**Comment by camrinbraun** [comment] 2019-12-06 17:06
@sdirix thanks for your help. can you be more specific for this solution? I manually edited one line in both `js.html` and `head.html` in the `layouts/partials` directory from `$script.RelPermalink` to `$script.Permalink` following the referenced commit with no improvement.

**Comment by sdirix** [comment] 2019-12-08 20:38
@camrinbraun I did nothing else than what you described :( Did you do the changes in your syna theme (like I did) or did you overwrite it in your partials? Do you maybe have an old copy in your partials so changes to the syna theme have no effect?

**Comment by sdirix** [comment] 2019-12-08 20:38
@mpourismaiel Is there an issue open in Hugo tracking this problem?

**Comment by camrinbraun** [comment] 2019-12-08 21:09
I took another deep dive here and figured out the issue. Indeed, the [commit](https://github.com/eclipsesource/syna/commit/db7d44890f0ed6f08b15cbb5d71d811255c80b31) you linked to did the trick. My additional issue was specifying additional pages like:

```
[[menu.main]]
  url = "/publications"
  name = "Publications"

```
instead of
```
[[menu.main]]
  url = "publications"
  name = "Publications"
```

Seems like the leading forward slash was causing the base url to be repeated regardless of the theme settings.

**Comment by mpourismaiel** [comment] 2019-12-16 14:00
I haven't created an upstream issue for this. @camrinbraun We're always happy for PRs.

**Comment by stp-ip** [comment] 2020-04-23 12:53
This is probably the Hugo issue related to this: https://github.com/gohugoio/hugo/issues/6073

We removed the relLangURL usage and therefore this should be fixed in the latest version. Please reopen, if this is not the case.

**Closed by stp-ip** 2020-04-23 12:53 UTC
Labels: bug

**Comment by sdirix** [comment] 2020-07-10 12:09
I can confirm that this is fixed! Thanks!
