### ISSUE TITLE
The "menu" doesn't work on smartphones

### ISSUE THREAD

**Issue by Tadeshi** [okkur/syna#710] opened 2020-02-09 15:45 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:

https://arahasmas.gitlab.io/psite2/ is build with syna. As you can see opening the link with a smartphone, the "menu" button (that with three lines on the upper right of the screen) it doesn't show anything.

**What you expected to happen**:

The button, once pressed, have to show the full menu of the site, namely the links to the pages "Home", "Chi siamo", "Blog" and "Contatti".

**How to reproduce it (as minimally and precisely as possible)**:

Just open the above link with your smartphone.

**Anything else we need to know?**:

The source of the site is at https://gitlab.com/arahasmas/psite2

**Environment**:
- Syna Theme version:
  + /themes/syna/VERSION = v0.16.1
- Hugo version:  
  + ````
     $ hugo version
       Hugo Static Site Generator v0.63.2-934EE21F/extended linux/amd64
       BuildDate: 2020-01-27T12:20:42Z
     ```
- Others:
  + Android on Samsung Galaxy A7
  + Android on Samsung S6

**Comment by mpourismaiel** [comment] 2020-02-20 11:55
The JS code required for the menu button to work is not loaded. The requested URL for it has fingerprint id in it and I take that to mean that Hugo has built and minified the resource but it either is not written to disk or is blocked by the backend.

Because #706 might be the same problem, I have to suggest trying to get a build of your website locally (we have `Makefile` and `package.json`, so `make` or `npm install && npm run build` both work) and using a simple web server such as [serve](https://www.npmjs.com/package/serve) to check whether or not the problem is your code, Hugo or Gitlab. I couldn't find a problem on your code as far as I looked. So my guess would mostly be Gitlab.

Let us know what happens and we can move from there.

**Comment by stp-ip** [comment] 2020-02-20 15:21
Gitlab doing minification and concatenation that breaks the JS?

**Comment by stp-ip** [comment] 2020-04-23 12:38
This should be fixed in the latest release.

**Closed by stp-ip** 2020-04-23 12:38 UTC
Labels: bug
