### ISSUE TITLE
Non http/https protocol links don't work

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#591] opened 2019-08-14 09:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When using a link such as "irc://irc.freenode.net/#syna" it will treat it as relative URL instead of absolute.

**Anything else we need to know?**:
Might be a hugo bug?

**Comment by mpourismaiel** [comment] 2019-08-17 10:06
This may be due to how `relLangURL` works. I think it's a Hugo bug. I'll read the code and get back to you.

**Comment by ConnorAYoh** [comment] 2019-12-02 09:38
I am also having this issue for using non HTTP/s links. Would be most useful to see this feature fixed

**Comment by stp-ip** [comment] 2019-12-02 11:40
Would be helpful to raise this within the upstream Hugo issue: https://github.com/gohugoio/hugo/issues/6244

**Comment by timokoch** [comment] 2020-07-02 13:12
I have an `item` fragment with a `buttons` section
```
[[buttons]]
  text = "Source code"
  url = "https://git.iws.uni-stuttgart.de/dumux-repositories/dumux"
  color = "primary"
```
Hugo prepends `/` to the url so I get the relative path
`/https://git.iws.uni-stuttgart.de/dumux-repositories/dumux`.

**What you expected to happen**:
Absolute urls stay absolute as documented here: https://gohugo.io/functions/relurl/

**How to reproduce it (as minimally and precisely as possible)**:
This only happens when I run `hugo` to generate the website (both development and production) and not in server development mode `hugo server -D`. I don't specify a baseURL in my config file.

**Anything else we need to know?**:
If I change the `relLangURL` in the syna `layouts/partials/fragments/item.html` button-related code to `relURL` or `absLangURL` everything works as expected. 

**Environment**:
- Syna Theme version:  v0.17.2
- Hugo version:  v0.73.0/extended from homebrew
- OS: macOS 10.13.6 (I also tested in a Docker container with ubuntu:20.04 -> same issue)

You explicitly mention that this issue occurs for you for non-http/https-protocols. But for me it also seems to happen for an `https` address. Am I missing something or does this issue (and the issue in hugo) have to be updated to include http/https-addresses? Any hint or assessment of the situation would be highly appreciated and thanks for the cool theme.

**Comment by stp-ip** [comment] 2020-07-02 13:28
This is a separate issue and feels like a bug. @mpourismaiel

**Comment by mpourismaiel** [comment] 2020-07-02 17:14
@timokoch I assume this is an expected behavior since you haven't added a `baseurl` value. Hugo uses that value to compare the link and learn whether or not the link is relative. When you remove that value, Hugo defaults to relative url mode.

This is not a bug in my view. And also the main issue, "Non http/https protocol links don't work", is not a bug we can do anything about. Both of these matters must be discussed in the [tracking issue](https://github.com/gohugoio/hugo/issues/6244) on Hugo's repository.

@stp-ip I think we can close this issue.

**Comment by stp-ip** [comment] 2020-07-02 17:28
Happy to revisit this in our backlog. Closed therefore.

**Closed** 2020-07-02 17:28 UTC
Labels: enhancement, revisit

**Comment by timokoch** [comment] 2020-07-02 18:54
> @timokoch I assume this is an expected behavior since you haven't added a `baseurl` value. Hugo uses that value to compare the link and learn whether or not the link is relative. When you remove that value, Hugo defaults to relative url mode.
> 
> This is not a bug in my view. And also the main issue, "Non http/https protocol links don't work", is not a bug we can do anything about. Both of these matters must be discussed in the [tracking issue](https://github.com/gohugoio/hugo/issues/6244) on Hugo's repository.
> 
> @stp-ip I think we can close this issue.

Ok thanks, so that means I just have to always supply a baseurl. I would still expect that hugo doesn't prepend anything to an address starting with `https://` because that never seems to make sense. But not a syna issue of course.
