### ISSUE TITLE
Move background style config to fragments

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#90] opened 2018-04-18 09:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently background style for footer and navbar are set within config.toml.

**What you expected to happen**:
Set these within their respective fragments.

**Comment by mpourismaiel** [comment] 2018-04-29 09:59
@stp-ip I think this one should be closed since the config is already available in the respective fragments and the problem lies with partials and I don't think there's a solution for those.

**Comment by mpourismaiel** [comment] 2018-05-06 16:47
@stp-ip I'm gonna close this. Open it if the issue is still valid.

**Comment by stp-ip** [comment] 2018-06-01 21:18
config.toml still has background_footer, which is unnecessary.

**Closed** 2018-06-02 16:17 UTC
Labels: enhancement
