### ISSUE TITLE
The button "Back to top" (from the closed issue #705 (https://github.com/okkur/syna/issues/705#))

### ISSUE THREAD

**Issue by Tadeshi** [okkur/syna#708] opened 2020-02-07 09:54 UTC
> The latest version of Syna is 0.16.1, which has a fix of this issue. ...

Same problem: https://arahasmas.gitlab.io/psite2/

/themes/syna/VERSION : v0.16.1 ( https://gitlab.com/arahasmas/psite2/-/blob/ba56b5a6be450c15b8f33534601ab87f03d0d899/themes/syna/VERSION )

_Originally posted by @Tadeshi in https://github.com/okkur/syna/issues/705#issuecomment-583314975_

**Comment by SeidoTakeshi** [comment] 2020-02-25 13:43
Trying to debug about the button "back to top" I've found that the
described behavior depends on the fiile `config.toml`

If `config.toml` has the following content (the three dots stand for the implied content):

```
baseurl = "/"
...
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/chi-siamo"
  name = "Chi Siamo"
  weight = 20

[[menu.main]]
  url = "/blog"
  name = "Blog"
  weight = 30

[[menu.main]]
  url = "/contatti"
  name = "Contatti"
  weight = 40
```

the button "back to top" works well. But if the content of the file `config.toml` is the following:

```
baseurl = "https://arahasmas.gitlab.io/psite4/"
...
[[menu.main]]
  url = ""
  name = "Home"
  weight = 10

[[menu.main]]
  url = "chi-siamo"
  name = "Chi Siamo"
  weight = 20

[[menu.main]]
  url = "blog"
  name = "Blog"
  weight = 30

[[menu.main]]
  url = "contatti"
  name = "Contatti"
  weight = 40
```
the button "back to top" doesn't work any more (nor locally nor on line).  So the site works well if I run it locally with hugo (and config.toml as the first example). But if I publish the site on gitlab (with config.toml as in the second example) the button "back to top" doesn't work.

**Comment by stp-ip** [comment] 2020-02-25 14:04
The back to top button and related issues are due to 404 errors I think. So in this specific case the JS needed for the back to top button isn't loadable.

Assumption is the path in baseurl is the issue. Will have to take a deeper look again at the latest "how to do hugo on gitlab" before I can help more I feel.

Maybe we don't support a sub directory in the baseurl well. @mpourismaiel ?

**Comment by SeidoTakeshi** [comment] 2020-02-25 15:45
> Assumption is the path in baseurl is the issue. Will have to take a
> deeper look again at the latest "how to do hugo on gitlab"
> before I can help more I feel.
> Maybe we don't support a sub directory in the baseurl well.

Maybe issue #710 is derived from the same problem.

**Comment by stp-ip** [comment] 2020-02-25 17:02
Yes I would say they are related as both might not work to the JS not being loaded, which in my view comes back to the resource 404ing, which you could reproduce with the different config of baseurl. So we have a few more details to try and debug.

**Comment by SeidoTakeshi** [comment] 2020-02-26 12:12
Some more information:

if the `baseurl` variable is

    baseurl = "/"

then the code of the generated page is

    <script src = "/scripts/syna-head.min.0757f18970a0a32d5acac5a2accc5fe82f787821866c545d9ed17ca765f291a3.js"> </script>

and the button "back to top" works well. if instead `baseurl` is

     baseurl = "https://arahasmas.gitlab.io/psite4/"

the code of the generated page is

    <script src = "/psite4/psite4/scripts/syna-head.min.0757f18970a0a32d5acac5a2accc5fe82f787821866c545d9ed17ca765f291a3.js"> </script>

and the button "back to top" doesn't work. Note the double `psite4/` at the beginning of the link: it is a directory that does not exist because the real directory should be `/psite4/scripts/syna-head.min.0757f18 ... .js`, or maybe only `/scripts/syna-head.min.0757f18 ... .js`.

**Comment by SeidoTakeshi** [comment] 2020-02-26 14:58
Forgive me if I'm boring, but I think I've found a possible solution. The problem appears to stem from a well-known [hugo bug](https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/8). The developers suggest using the following solution at least temporarily:

     RelativeURLs = true
     CanonifyURLs = true

that seems to work.

**Comment by stp-ip** [comment] 2020-02-26 15:36
Great so it seems this is a bug within Hugo not Syna. We might wanna document this issue with subdirectories within the baseurl in the config file so we don't get new reports on this. @mpourismaiel ?

We'll reiterate and most likely close all these related issues and happy that you have a workaround for this issue. \o/

**Comment by stp-ip** [comment] 2020-04-23 12:55
This should be fixed by the recent removal of relLangURL on asset urls. Please reopen, if it still persists.

**Closed by stp-ip** 2020-04-23 12:55 UTC
